#!/usr/bin/python2.7
from hosted import device, node, config, requests, time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(11, GPIO.IN)
  
# defining the api-endpoint  
API_ENDPOINT = "https://industrial.api.ubidots.com/api/v1.6/variables/5bc42e241d847237ab064bdc/values/"

# defining token header 
headers = {'X-Auth-Token':'BBFF-6TNiXhGp4El0w1AeDddt719Ti8KShm', 'Content-Type':'application/json'} 
  
# people counter while an asset is running - should send an API call with increment of people after every asset ran
counter = 0
peoplecount = 0
while(1):
    presence = GPIO.input(11)
    if(presence):
        peoplecount += 1
        presence = 0
        time.sleep(1.5)
    time.sleep(1)
    counter += 1
    if(counter==10):
        print peoplecount
        # data to be sent to api with timestamp and get the current running asset id
        data = {
                "value": peoplecount,
                "timestamp": time.time(),
                "context": {
  	              "asset_id": 34533,
                  "device_id": <device id or serial>
                            }
                }
        # sending post request and saving response as response object 
        r = requests.post(url = API_ENDPOINT, data = data, headers=headers) 
        counter = 0
        peoplecount = 0
